### ISSUE TITLE
websocket port does not match with your homebridge project

### ISSUE THREAD

**Issue by karaoak** [henry-spanka/freeathome-api#5]
Great job! Thank you so much for getting your hands dirty and creating this api.

It took me some time to get things working, as in your freeathome-api example config.json you use a wsApi port **8081**, while in your https://github.com/henry-spanka/homebridge-buschjaeger documentation and default setup you use port **8001**. 

Once I figured this out, everything works great with Busch-Jaeger's SysAP version 2.3.1
Thank you so much.

So not really opening an issue here, rather a suggestion to point out the above in your readme

Kind regards, Frank

**Comment by henry-spanka** [comment]
Hi Frank,
thanks for the update.

I am aware of this and it's already documented in https://github.com/henry-spanka/homebridge-buschjaeger#setup--installation. 8001 is a reserved port (Shoutcast). That's why the ports are now 8080 and 8081 by default. I also think it makes more sense to group them together (easier firewall rules etc.). You can of course always change them to whatever you want. I may update the homebridge plugin in the future to connect to 8081 by default, and/or allow the user to change the port in the homebridge config.
